name: Service Status Check

on:
  schedule:
    - cron: "1,25,55 * * * *"

  workflow_dispatch:

jobs:
  service-check:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    name: Check knloop service status
    env:
      WEBHOOK_KEY: ${{ secrets.WECHAT_WEBHOOK_KEY }}
      PUSH_ENABLED: ${{ secrets.PUSH_ENABLED }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: page

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache-dependency-path: checkshell/go.sum

      - name: Run Service Check
        id: service_check_run
        working-directory: ./checkshell
        run: |
          go mod download
          go run .

      - name: Commit and push changes
        run: |
          git config --local user.name 'Github Actions'
          git config --local user.email 'Actions@knloop.com'
          git add -A --force ./logs/
          git commit -m '🆙 [Automated] Update service status logs'
          git push origin page
